# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pqSearchCpp <- function(query, compressed_data, centroids) {
    .Call('_BA23229020_pqSearchCpp', PACKAGE = 'BA23229020', query, compressed_data, centroids)
}

